# Documentation and sources
# - https://docs.github.com/en/enterprise-server@3.14/actions/about-github-actions/about-continuous-integration-with-github-actions
# - https://docs.github.com/en/enterprise-server@3.14/actions/learn-github-actions/workflow-syntax-for-github-actions
# - https://code.visualstudio.com/api/working-with-extensions/continuous-integration

name: Deploy to VSCode Marketplace

on:
  push:
    branches:
      - main
  release:
    types:
    - created
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - run: npm install
    # - run: xvfb-run -a npm test
    #   if: runner.os == 'Linux'
    # - run: npm test
    #   if: runner.os != 'Linux'
    - name: Publish
      if: success() && startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
    